package co.edu.uniquindio.proyecto.modelo;

public enum Ciudad{
    BOGOTA,
    MEDELLIN,
    CALI,
    BARRANQUILLA,
    CARTAGENA,
    CUCUTA,
    BUCARAMANGA,
    PEREIRA,
    SANTA_MARTA,
    IBAGUE,
    MANIZALES,
    PASTO,
    MONTERIA,
    VILLAVICENCIO,
    ARMENIA,
    NEIVA,
    POPAYAN,
    VALLEDUPAR,
    SINCELEJO,
    RIOHACHA,
    TUNJA,
    FLORENCIA,
    QUIBDO,
    MITU,
    INIRIDA,
    SAN_JOSE_DEL_GUAVIARE,
    LETICIA,
    YOPAL
}